name: Test

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  test:
    strategy:
      matrix:
        go-version: [ 1.24.x ]
        os: [ ubuntu-22.04 ]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 5
    steps:
      - name: Install Go
        uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5.5.0
        with:
          go-version: ${{ matrix.go-version }}

      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Go Module Download
        working-directory: ${{ env.testdir }}
        run: |
          go install gotest.tools/gotestsum@latest

      - name: Test
        working-directory: ${{ env.testdir }}
        timeout-minutes: 3
        run: |
          gotestsum -- -race ./...
